CREATE TABLE IF NOT EXISTS `tag1` (
   `artist1` VARCHAR(40) NOT NULL,
   `info1` VARCHAR(400) NOT NULL,
   `location1` VARCHAR(40) NOT NULL,
   `song1` VARCHAR(40) NOT NULL,

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

