CREATE TABLE IF NOT EXISTS `tag3` (
   `artist3` VARCHAR(40) NOT NULL,
   `info3` VARCHAR(400) NOT NULL,
   `location3` VARCHAR(40) NOT NULL,
   `song3` VARCHAR(40) NOT NULL,

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

