<?php
echo "<!DOCTYPE HTML>
<html>
   <head>
      <meta charset='utf-8'>
      <title>Form Submission Success</title>
      <link rel='stylesheet' href='css/normalize.css'>
      <link rel='stylesheet' href='css/style.css'>
   </head>
   <body>
      <h1>Form Submission Success</h1>
      <p>You’ve successfully submitted your form. Click <a href='./index.php'>here</a> to go back to the home page, or you can simply wait 5 seconds to be redirected.</p>
   </body>
</html>
";
